name: Feishu OAuth Handler
on: 
  repository_dispatch:
    types: [feishu_oauth]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Exchange code for token
        run: |
          CODE=${{ github.event.client_payload.code }}
          RESPONSE=$(curl -X POST https://open.feishu.cn/open-apis/authen/v1/access_token \
            -H "Content-Type: application/json" \
            -d '{"grant_type":"authorization_code","code":"'$CODE'","app_id":"你的AppID","app_secret":"你的AppSecret"}')
          echo "TOKEN_RESPONSE=$RESPONSE" >> $GITHUB_ENV
      
      - name: Save token
        run: |
          echo "${{ env.TOKEN_RESPONSE }}" > token.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add token.json
          git commit -m "Update token"
          git push
